eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: pact-test

server:
  port: 8080

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server/eureka/

server:
  port: 9020
